// generate a list of words with over 3 vowels

var words = [
    "abacus",
    "apple",
    "banana",
    "cat",
    "dog",
    "elephant",
    "flower",
    "guitar",
    "happiness",
    "island",
    "jazz",
    "koala",
    "laptop",
    "mountain",
    "notebook",
    "ocean",
    "piano",
    "queen",
    "river",
    "sun",
    "tiger",
    "umbrella",
    "violin",
    "water",
    "xylophone",
    "yoga",
    "zebra",
    "active",
    "beautiful",
    "creative",
    "dolphin",
    "eagle",
    "fountain",
    "garden",
    "honey",
    "ice cream",
    "juice",
    "kangaroo",
    "lemon",
    "moon",
    "nature",
    "oxygen",
    "peacock",
    "quiet",
    "rainbow",
    "sunset",
    "tree",
    "unicorn",
    "violet",
    "whale",
    "xylophone",
    "yummy",
    "zealous",
    "ant",
    "bee",
    "caterpillar",
    "duck",
    "elephant",
    "frog",
    "grasshopper",
    "hippopotamus",
    "insect",
    "jellyfish",
    "koala",
    "ladybug",
    "monkey",
    "nightingale",
    "octopus",
    "penguin",
    "queen bee",
    "rabbit",
    "snail",
    "tortoise",
    "unicorn",
    "vulture",
    "whale",
    "x-ray fish",
    "yak",
    "zebra",
    "air",
    "breath",
    "cloud",
    "dream",
    "echo",
    "feather",
    "glow",
    "hope",
    "ice",
    "joy",
    "kiss",
    "love",
    "moonlight",
    "nest",
    "oasis",
    "peace",
    "quiet",
    "rain",
    "star",
    "twinkle",
    "universe",
    "vibrant",
    "whisper",
    "xenon",
    "yawn",
    "zen"
  ];
  

wordOfTheDay = words[Math.floor(Math.random() * words.length)];

wordNoVowels = wordOfTheDay.replace(/[aeiou]/gi, '');

document.getElementById("conson").innerHTML = wordNoVowels + " " + wordOfTheDay.length;